server:
  port: 8080
  servlet:
    contextPath: /${spring.application.name}/v1
spring:
  application:
    name: mssivimss-ord-servicios
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

      
  datasource:
    platform: mariadb
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SIVIBDDS9?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=America/Mexico_City #jdbc:mysql://10.102.44.18:3306/SIVIBDDS
    username: SIVI_USER #pmsoluciones #root
    password: 51V1_US3R #Tr1357.* #Maria2023
    timeBetweenEvictionRunsMillis: 1000
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
       max-lifetime: 1800000
       idle-timeout: 600000
       connection-timeout: 30000
       auto-commit: false
       maximum-pool-size: 7
       minimum-idle: 10

  main:
    allow-circular-references: true
    
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

logos:
  msit_logo_imss: /sintrans_data/LOGOS/logoImss.png
  msit_logo_sistema: /sintrans_data/LOGOS/logoSistema.png

endpoints:
   mod-catalogos: "http://localhost:8090/mssivimss-mod-catalogos/v1/generico"
   ms-reportes: "http://localhost:8088/mssivimss-reportes-jpr"
   renapo: "http://serviciosdigitalesinterno-stage.imss.gob.mx/serviciosDigitales-rest/v1/externos/renapo/curp"

jwt:
  secretkey-flujo: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360
  
management:
      endpoints:
          web:
            exposure:
                include:
                    health,info,metrics

resilience4j.circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      msflujo:
        automaticTransitionFromOpenToHalfOpenEnabled: 'true'
        failureRateThreshold: '50'
        slidingWindowType: COUNT_BASED
        event-consumer-buffer-size: '10'
        registerHealthIndicator: 'true'
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: '3'
        slidingWindowSize: '5'
resilience4j.retry:
    retryAspectOrder: 2
    instances:
        msflujo:
           maxAttempts: 3
           waitDuration: 5s
resilience4j.timelimiter:
    timeLimiterAspectOrder: 3
    instances:
      msflujo:
        timeout-duration: 3s
        
        
formato_fecha: '%d/%m/%Y'
ruta-log: 'C:/logs/'